name: Deploy to Lambda

on:
  push:
    branches: [ main ]  # Triggers the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu virtual machine

    steps:
    # Step 1: Checkout the code from GitHub repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python 3.9 environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies and zip the Lambda function
    - name: Install Dependencies and Zip
      run: |
        pip install -r lambda/requirements.txt -t lambda/package  # Install dependencies into lambda/package/
        cp lambda/lambda_function.py lambda/package/              # Copy your lambda_function.py into lambda/package/
        cd lambda/package
        zip -r ../function.zip .                                   # Create a ZIP of your Lambda code
        cd ../..

    # Step 4: Deploy the zipped Lambda code to AWS Lambda using a custom action
    - name: Deploy Lambda
      uses: appleboy/lambda-action@master  # Uses the appleboy lambda-action to deploy
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Use GitHub Secrets for AWS credentials
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1                                     # Specify your AWS region
        function_name: HelloLambda                             # Name of the Lambda function you want to deploy to
        zip_file: lambda/function.zip                           # Path to the zip file containing the function
